GoodBurger/Controllers/HomeController.cs
using System.Web.Mvc;

namespace GoodBurger.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

      
        public ActionResult Contact()
        {
            ViewBag.Message = "Nos coordonnés";

            return View();
        }
    }
}

GoodBurger/Controllers/RegisterController.cs
using GoodBurger.Classes;
using GoodBurger.Models.DAL;
using GoodBurger.Models.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;


namespace GoodBurger.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        private UserDal DalUser = new UserDal();
        private TownDal DalTown = new TownDal();

        /// <summary>
        /// Get index view
        /// </summary>
        /// <returns>View</returns>
        // GET: Register
        public ActionResult Index()
        {
            List<TownEntity> AllTown = DalTown.GetAllTown();
            ViewData["AllTown"] = AllTown;
            return View("Index");
        }

        /// <summary>
        /// Check and add new user in data base
        /// </summary>
        /// <param name="dataForm">FormCollection</param>
        /// <returns>View</returns>
        //Post : Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(FormCollection dataForm)
        {
           try
           {  
                    string firstName = dataForm["FirstName"];
                    string lasttName = dataForm["LastName"];
                    int phone = int.Parse(dataForm["Phone"]);
                    string email = dataForm["Email"];
                    string password = PasswordHandler.MD5Hash(dataForm["Password"]);
                    string address = dataForm["Email"];
                    int postalCode = int.Parse(dataForm["PostalCode"]);
                    long townId = long.Parse(dataForm["Town"]);

                if (!DalUser.RegisterUser(firstName, lasttName, phone, email, password, address, postalCode, townId).Equals(0))
                    {
                        return RedirectToAction("Index", "Login");
                    }
 
            } catch (Exception e) {
               ModelState.AddModelError("Error in register action", e.Message);
            }

            return View("Index");
        }

    }
}

GoodBurger/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contactez nous";
}
<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        Quartier Develeppement<br />
       75000 Paris <br />
        <abbr title="Phone">P:</abbr>
        04.05.06.07.08
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>

</div>

GoodBurger/Views/Home/Index.cshtml
@model GoodBurger.Models.Entities.RestaurantEntity
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="center-align">
        <img class="iconBurger" src="~/Content/img/burger-icon.svg" alt="burger" />
        <h1><span class="go HomeSizeIcon">GO</span><span class="od HomeSizeIcon">OD</span><span class="bu HomeSizeIcon">BU</span><span class="rg HomeSizeIcon">RG</span><span class="er HomeSizeIcon">ER</span></h1>

        <p>
           GoodBuger est un site internet fantastique pour trouver le meilleur burger dans votre ville.<br />
           Faites vous livrer et dégustez votre délicieux burger .
        </p>
        <p><a class="waves-effect waves-light btn-large" href="#" role="button" onclick="window.location='@Url.Action("Index", "Register")'">Inscription</a></p>

    </div>

    <div class="row">
        <div class="col s12 m6">
            <div class="icon-block">
                <h2 class="center light-blue-text"><i class="HomeSizeIcon material-icons" >restaurant_menu</i></h2>
                <h5 class="center">Lorem</h5>

                <p class="light">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux </p>
            </div>
        </div>

  
        <div class="col s12 m6">
            <div class="icon-block">
                <h2 class="center light-blue-text"><i class="HomeSizeIcon material-icons">timelapse</i></h2>
                <h5 class="center">Lorem</h5>

                <p class="light">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux </p>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img class="cityImg" src="~/Content/img/paris.jpg">
                    <span class="card-title">PARIS</span>
                    <a class="btn-floating halfway-fab waves-effect waves-light green"><i class="material-icons" onclick="window.location='@Url.Action("AllRestaurant", "Restaurant", new RouteValueDictionary(new { nameTown = "Paris"}))'">add</i></a>
                </div>
                <div class="card-content">
                    <p>  Restaurants à Paris</p>
                </div>
            </div>
        </div>

        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img  class="cityImg"  src="~/Content/img/marseille.jpg">
                    <span class="card-title">MARSEILLE</span>
                    <a class="btn-floating halfway-fab waves-effect waves-light blue"><i class="material-icons" onclick="window.location='@Url.Action("AllRestaurant", "Restaurant", new RouteValueDictionary(new { nameTown = "Marseille"}))'">add</i></a>
                </div>
                <div class="card-content">
                    <p>  Restaurants à Marseille</p>
                </div>
            </div>
        </div>

        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img  class="cityImg"  src="~/Content/img/Strasbourg.jpg">
                    <span class="card-title">STRASBOURG</span>
                    <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons" onclick="window.location='@Url.Action("AllRestaurant", "Restaurant", new RouteValueDictionary(new { nameTown = "Strasbourg"}))'">add</i></a>
                </div>
                <div class="card-content">
                    <p>  Restaurants à Strasbourg</p>
                </div>
            </div>
        </div>

        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img class="cityImg"  src="~/Content/img/troyes.jpg">
                    <span class="card-title">TROYES</span>
                    <a class="btn-floating halfway-fab waves-effect waves-light orange"><i class="material-icons" onclick="window.location='@Url.Action("AllRestaurant", "Restaurant", new RouteValueDictionary(new { nameTown = "Troyes"}))'">add</i></a>
                </div>
                <div class="card-content">
                    <p>  Restaurants à Troyes</p>
                </div>
            </div>
        </div>

        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img class="cityImg" src="~/Content/img/Bordeaux.jpg">
                    <span class="card-title">BORDEAX</span>
                    <a class="btn-floating halfway-fab waves-effect waves-light purple"><i class="material-icons"  onclick="window.location='@Url.Action("AllRestaurant", "Restaurant", new RouteValueDictionary(new { nameTown = "Bordeaux"}))'" >add</i></a>
                </div>
                <div class="card-content">
                    <p>  Restaurants à Bordeaux</p>
                </div>
            </div>
        </div>

    </div>
</div>