GoodBurger/Controllers/DirectorController.cs
using GoodBurger.Classes;
using GoodBurger.Models.DAL;
using GoodBurger.Models.Entities;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;

namespace GoodBurger.Controllers
{ 
    [Authorize]
    public class DirectorController : Controller
    {
        private DirectorDal DalDirector = new DirectorDal();
        private DirectorEntity Director = new DirectorEntity();
        private RestaurantDal DalRestaurant = new RestaurantDal();
        private OrderDal DalOrder = new OrderDal();
        private DrinkDal DalDrink = new DrinkDal();
        private BurgerDal DalBurger = new BurgerDal();

        // GET: OwnerRestaurant
        /// <summary>
        /// Get view index Director
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public ActionResult Index()
        {
            List<DirectorEntity> AllOwner = DalDirector.GetAllDirectors();
            ViewData["AllOwner"] = AllOwner;
            return View();
        }

        /// <summary>
        /// Get home Director view
        /// </summary>
        /// <returns>View</returns>
        public ActionResult HomeDirector()
        {
            string CurrentCookie = HttpContext.User.Identity.Name;
            long idUser = long.Parse(CurrentCookie);
            Director  = DalDirector.GetOwnerById(idUser);
            List<OrderEntity> Orders = DalOrder.GetAllOrderByIdRestaurant(Director.CurrentRestaurantId);
            ViewData["Orders"] = Orders;
            List<DrinkEntity> Drinks = DalDrink.GetAllDrinksInRestaurant(Director.CurrentRestaurantId);
            ViewData["Drinks"] = Drinks;
            List<BurgerEntity> Burgers = DalBurger.GetAllBurgerInRestaurant(Director.CurrentRestaurantId);
            ViewData["Burgers"] = Burgers;

            List<DrinkEntity> StockWarningDrink = new List<DrinkEntity>();
            List<BurgerEntity> StockWarningBurger = new List<BurgerEntity>();
            foreach (DrinkEntity Drink in Drinks)
            {
                if (Drink.Stock <= 20)
                {
                    
                    StockWarningDrink.Add(Drink);
                    ViewData["StockWarningDrink"] = StockWarningDrink;
                }
               
            }

            foreach (BurgerEntity Burger in Burgers)
            {
                if (Burger.Stock <= 20)
                {

                    StockWarningBurger.Add(Burger);
                    ViewData["StockWarningBurger"] = StockWarningBurger;
                }
                
            }

            return View();
        }

        /// <summary>
        /// Check and log director
        /// </summary>
        /// <param name="dataForm">FormCollection</param>
        /// <returns>RedirectToAction</returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection dataForm)
        {
            try
            {
                DirectorDal dal = new DirectorDal();
                string email = dataForm["Email"];
                string password = PasswordHandler.MD5Hash(dataForm["Password"]);
                Director = dal.CheckIfOwnerExist(email, password);
          
                if (Director != null)
                {
          
                    HttpContext.Session["Role"] = "Directors";
                    FormsAuthentication.SetAuthCookie(Director.UserID.ToString(), false);
                    return RedirectToAction("HomeDirector", "Director");
                }

               

            }
            catch (Exception e)
            {
               ModelState.AddModelError("Error", e.Message);
            }
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Get form director
        /// </summary>
        /// <returns>View</returns>
        public ActionResult FormAddDirector()
        {

            List<DirectorEntity> Directors = DalDirector.GetAllDirectors();
            List<RestaurantEntity> AllRestaurant = DalRestaurant.GetAllRestaurant();
            
            ViewData["AllRestaurant"] = AllRestaurant;
            return View();
        }

        /// <summary>
        /// Get form login
        /// </summary>
        /// <returns>View</returns>
        [AllowAnonymous]
        public ActionResult FormLogin()
        {
            return View();
        }

        /// <summary>
        /// Check and add director in data base
        /// </summary>
        /// <param name="dataForm">FormCollection</param>
        /// <returns>RedirectToAction</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(FormCollection dataForm)
        {
            try
            {
                string firstName = dataForm["FirstName"];
                string lasttName = dataForm["LastName"];
                int phone = int.Parse(dataForm["Phone"]);
                string email = dataForm["Email"];
                string password = PasswordHandler.MD5Hash(dataForm["Password"]);
                string address = dataForm["Address"];
                int postalCode = int.Parse(dataForm["PostalCode"]);
                string city = dataForm["City"];
                long IdRestaurant = long.Parse(dataForm["IdRestaurant"]);

                string CurrentCookie = HttpContext.User.Identity.Name;
                long idAdmin = long.Parse(CurrentCookie);

                DirectorEntity owner = new DirectorEntity(firstName, lasttName, phone, email, password, address, postalCode, city, idAdmin, IdRestaurant);

                if (owner != null)
                {
                    long idOwer = DalDirector.Add(owner);
                    if (!idOwer.Equals(0))
                    {
                        List<DirectorEntity> AllOwner = DalDirector.GetAllDirectors();
                        ViewData["AllOwner"] = AllOwner;
                        return RedirectToAction("Index", "Director");
                    }

                }
            }

            catch (Exception e)
            {
                ModelState.AddModelError("Error in register action", e.Message);
            }

            return RedirectToAction("Index", "Director");
        }

        /// <summary>
        /// Get from update udirector
        /// </summary>
        /// <param name="DirectorId">long</param>
        /// <returns>View</returns>
        public ActionResult FormUpdateDirector(long DirectorId)
        {
            if (!DirectorId.Equals(0))
            {
                DirectorEntity Owner = DalDirector.GetOwnerById(DirectorId);
                return View(Owner);
            }
           
            return View();
        }

        /// <summary>
        /// Remove director from data base
        /// </summary>
        /// <param name="DirectorId">long</param>
        /// <returns>RedirectToAction</returns>
        [HttpGet]
        public ActionResult Remove(long DirectorId)
        {
            if (!DirectorId.Equals(0))
            {
                DirectorEntity Owner = DalDirector.GetOwnerById(DirectorId);
                DalDirector.Remove(Owner);
                
            }
            return RedirectToAction("Index", "Director");
        }

        /// <summary>
        /// check and update data director
        /// </summary>
        /// <param name="dataForm">FormCollection</param>
        /// <param name="DirectorId">long</param>
        /// <returns>RedirectToAction</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(FormCollection dataForm, long DirectorId)
        {
            DirectorEntity Director = DalDirector.GetOwnerById(DirectorId);


            if (dataForm != null)
            {

                Boolean Isdifferent = false;
                string firstName = dataForm["FirstName"];
                string lasttName = dataForm["LastName"];
                int phone = int.Parse(dataForm["Phone"]);
                string email = dataForm["Email"];
                string password = dataForm["Password"];
                string address = dataForm["Address"];
                int postalCode = int.Parse(dataForm["PostalCode"]);
                string city = dataForm["City"];

                if (Director != null)
                {

                    if (firstName != Director.FirstName)
                    {
                        Director.FirstName = firstName;
                        Isdifferent = true;
                    }

                    if (lasttName != Director.LastName)
                    {
                        Director.LastName = lasttName;
                        Isdifferent = true;
                    }
                    if (phone != Director.Phone)
                    {
                        Director.Phone = phone;
                        Isdifferent = true;
                    }
                    if (email != Director.Email)
                    {
                        Director.Email = email;
                        Isdifferent = true;
                    }

                    if (password != Director.Password)
                    {
                        Director.Password = password;
                        Isdifferent = true;
                    }

                    if (address != Director.Address)
                    {
                        Director.Address = address;
                        Isdifferent = true;
                    }
                    if (city != Director.City)
                    {
                        Director.City = city;
                        Isdifferent = true;
                    }
                    if (postalCode != Director.PostalCode)
                    {
                        Director.PostalCode = postalCode;
                        Isdifferent = true;
                    }

                    if (Isdifferent == true)
                    {

GoodBurger/Controllers/OrderController.cs
using GoodBurger.Models.DAL;
using GoodBurger.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace GoodBurger.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private OrderDal DalOrder = new OrderDal();
        private DirectorDal DalDirector = new DirectorDal();
        private DirectorEntity Director = new DirectorEntity();
        /// <summary>
        /// Get idnex view
        /// </summary>
        /// <returns>View</returns>
        // GET: Order
        public ActionResult Index()
        {
            string CurrentCookie = HttpContext.User.Identity.Name;
            long idUser = long.Parse(CurrentCookie);
            List<OrderEntity> Orders = new List<OrderEntity>();
            Orders = DalOrder.GetAllOrders().OrderByDescending(r => r.DateOrder.Date).ToList();
            ViewData["Orders"] = Orders;
            return View();
        }

        /// <summary>
        ///Get all order
        /// </summary>
        /// <param name="allOrder">bool?</param>
        /// <param name="monthOrder">bool?</param>
        /// <param name="day">bool?</param>
        /// <returns>View</returns>
        public ActionResult SeeAllOrder(bool? allOrder,bool? monthOrder, bool? day)
        {
            string CurrentCookie = HttpContext.User.Identity.Name;
            long IdDirector = long.Parse(CurrentCookie);
            Director = DalDirector.GetOwnerById(IdDirector);
            long idRestaurant = Director.CurrentRestaurantId;
            int Day = DateTime.Now.Day;
            int  Month = DateTime.Now.Month;

            if (Director != null && allOrder != null) 
            {
                List<OrderEntity> Orders = DalOrder.GetAllOrderByIdRestaurant(idRestaurant).OrderByDescending(date => date.DateOrder).ToList();
                ViewData["Orders"] = Orders;
            }
            if (Director != null && monthOrder != null)
            {
                List<OrderEntity> OrderThisMonth = DalOrder.GetAllOrderByIdRestaurant(idRestaurant).Where(d => d.DateOrder.Month == Month).ToList();
                ViewData["Orders"] = OrderThisMonth;
            }


            if (Director != null && day != null)
            {
                List<OrderEntity> DayOrders = DalOrder.GetAllOrderByIdRestaurant(idRestaurant).Where(d => d.DateOrder.Day == Day).ToList();
                ViewData["Orders"] = DayOrders;
            }

            return View();
        }

        
    }
}

GoodBurger/Views/Director/FormAddDirector.cshtml
@model GoodBurger.Models.Entities.DirectorEntity
@{
    ViewBag.Title = "Formulaire directeur";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <div class="alert alert-success" role="alert">
        <p>Attention ajouter le restaurant avant de créer le directeur !</p>
        <p>Vous devez obligatoirement associer un directeur à un restaurant  </p>
    </div>

    @using (Html.BeginForm("Add", "Director", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row ">
            <div class="col s12">
                <div class="input-field col s12">

                    @Html.Label("Nom")
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Prénom")
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Tél")
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", Type = "tel" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Email")
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", Type = "email" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Mot de passe")
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control", Type = "password" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Adresse")
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Code postal")
                    @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control", Type = "number", step = "1", value = "0", min = "0", max = "99999" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Ville")
                    @Html.TextBoxFor(m => m.City, new { @class = "form-control", Type = "text" })
                </div>
                <br />
            </div>
        </div>
        @Html.Partial("~/Views/Restaurant/ListRestaurant.cshtml", @ViewData["AllRestaurant"])
        <button type="submit" class="btn blue">Valider</button>
        <button type="button" class="btn  red" onclick="window.location='@Url.Action("Index", "Director")'">Annuler</button>
    }
</div>

GoodBurger/Views/Director/FormLogin.cshtml
@model GoodBurger.Models.Entities.DirectorEntity

@{
    ViewBag.Title = "Connexion du directeur";
}

<div class="container">
    <h2>@ViewBag.Title</h2>
    @using (Html.BeginForm("Login", "Director", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row ">
            <div class="col s12">
                <div class="input-field">
             
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", Type = "email" })
                </div>
                <div class="input-field">
         
                    @Html.LabelFor(m => m.Password)
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control", Type = "password" })
                </div>
                <button type="submit" class="btn btn-primary">Valider</button> <button type="button" class="btn btn-outline-success" onclick="window.location='@Url.Action("Index", "Home")'">Accueil</button>
            </div>
         </div>
    }


</div>

GoodBurger/Views/Director/FormUpdateDirector.cshtml
@model GoodBurger.Models.Entities.DirectorEntity
@{
    ViewBag.Title = "Formulaire modification directeur";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm("Update", "Director", new RouteValueDictionary(new { DirectorId = @Model.DirectorId }), FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row ">
            <div class="col s12">
                <div class="input-field col s12">

                    @Html.Label("First Name")
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Last Name")
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Phone")
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", Type = "tel" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Email")
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", Type = "email" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Password")
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control", Type = "password" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Address")
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control", Type = "text" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("Postal Code")
                    @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control", Type = "number", step = "1", value = "0", min = "0", max = "99999" })
                </div>

                <div class="input-field col s12">

                    @Html.Label("City")
                    @Html.TextBoxFor(m => m.City, new { @class = "form-control", Type = "text" })
                </div>
                <br />
            </div>
        </div>
        <button type="submit" class="btn blue">Valider</button>
        <button type="button" class="btn  red" onclick="window.location='@Url.Action("Index", "Director")'">Annuler</button>
    }
</div>

GoodBurger/Views/Director/HomeDirector.cshtml
@using GoodBurger.Models.Entities
@using GoodBurger.Models.DAL
@{
    ViewBag.Title = "Tableau de bord";
    List<DrinkEntity> StockWarningDrink = ViewData["StockWarningDrink"] as List<DrinkEntity>;
    List<BurgerEntity> StockWarningBurger = ViewData["StockWarningBurger"] as List<BurgerEntity>;

    List<DrinkEntity> AllDrinks = ViewData["Drinks"] as List<DrinkEntity>;
    List<BurgerEntity> AllBurgers = ViewData["Burgers"] as List<BurgerEntity>;
    List<OrderEntity> AllOrdes = ViewData["Orders"] as List<OrderEntity>;

    float SumOrder = 0;
}

<div class="container">

    <h2>@ViewBag.Title</h2>


    <div>
        <h4>Information Génériques : </h4>
        <table>
            <thead>
                <tr>
                    <th>Nombre de commande engeristrée </th>
                    <th>Montant cumulé des commandes</th>
                    <th>Nombre de burger enregistré</th>
                    <th>Nombre de boisson enregistrée</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td> @AllOrdes.Count</td>
                    <td>
                        @foreach (OrderEntity Order in AllOrdes)
                        {
                            SumOrder += Order.SumOrder;
                        }
                        @SumOrder
                    </td>
                    <td>@AllBurgers.Count</td>
                    <td>@AllDrinks.Count </td>
                </tr>

            </tbody>
        </table>

    </div>

    <div>
        <h4>les commandes :  </h4>
        <table>

            <thead>
                <tr>
                    <th>Toutes</th>
                    <th>Du mois en cour </th>
                    <th>De la journée</th>

                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>
                        <button type="button" class="btn" onclick="window.location='@Url.Action("SeeAllOrder", "Order", new RouteValueDictionary(new { allOrder = true }))'">Toutes </button>
                    </td>
                   
                    <td>
                        <button type="button" class="btn" onclick="window.location='@Url.Action("SeeAllOrder", "Order", new RouteValueDictionary(new { monthOrder = true }))'">Du mois en cour </button>
                    </td>
                    <td>
                        <button type="button" class="btn" onclick="window.location='@Url.Action("SeeAllOrder", "Order", new RouteValueDictionary(new { day = true }))'">De la journée</button>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>



    @if (StockWarningDrink != null)
    { 
        <div class="card-panel grey lighten-3">
            @foreach (DrinkEntity Drink in StockWarningDrink)
            {
                <hr />
                <p>Boisson : @Drink.Name</p>
                <p class="text-warning">Stock restant : @Drink.Stock</p>
                <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("FormUpdateDrink", "Drink", new RouteValueDictionary(new { DrinkId = Drink.DrinkId }))'">Update</button>
            }
        </div>
    }
    else
    {
        <div class="card-panel grey lighten-3">
            <h4>Vos stock de boisson dépasse les 20 unités pour tous vos produit ! </h4>
            <strong> Cependant soyez à l'affût des futurs manques possible ! </strong>
        </div>
    }

    @if (StockWarningBurger != null)
    {

        <div class="card-panel grey lighten-3">
            @foreach (BurgerEntity Burger in StockWarningBurger)
            {
      
                <p>Burger : @Burger.Name</p>
                <p class="text-warning">Stock restant : @Burger.Stock</p>
                <button type="button" class="btn btn-success" onclick="window.location='@Url.Action("FormUpdateBurger", "Burger", new RouteValueDictionary(new { BurgerId = Burger.BurgerId }))'">Update</button>
            }
        </div>
    }
    else
    {
        <div class="card-panel grey lighten-3">
            <h4>Vos stock de burger dépasse les 20 unités pour tous vos produit !</h4>
            <strong>Cependant soyez à l'affut des futurs manques possible !</strong>
        </div>
    }
</div>

GoodBurger/Views/Director/Index.cshtml
@model GoodBurger.Models.Entities.DirectorEntity
@using GoodBurger.Models.Entities
@{
    ViewBag.Title = "Director Restaurant";
    List<DirectorEntity> AllOwners = ViewData["AllOwner"] as List<DirectorEntity>;
}

<div class="container">
    <h2>@ViewBag.Title</h2>
    <div>
        <button type="button" class="btn btn-primary" onclick="window.location='@Url.Action("FormAddDirector", "Director")'">Ajouter un directeur</button>
    </div>
    @if (!AllOwners.Any())
    {
        <div class="alert alert-warning" role="alert">
            <strong> No Director Register</strong>
        </div>
    }
    else
    {
        <table>
            <thead>
                <tr>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                    <th>Adresse</th>
                    <th>Code postal</th>
                    <th>Ville</th>
                    <th>Gestion</th>
                </tr>
            </thead>

            @foreach (DirectorEntity Director in AllOwners)
            {
                <tbody>
                    <tr>
                        <td>@Director.LastName</td>
                        <td>@Director.FirstName</td>
                        <td>@Director.Email</td>
                        <td>+33 @Director.Phone</td>
                        <td>@Director.Address</td>
                        <td>@Director.PostalCode</td>
                        <td>@Director.City</td>
                        <td>
                            <button type="button" class="btn  red" onclick="window.location='@Url.Action("Remove", "Director", new RouteValueDictionary(new { DirectorId = Director.DirectorId }))'">Suprimer</button>
                            <button type="button" class="btn  blue" onclick="window.location='@Url.Action("FormUpdateDirector", "Director", new RouteValueDictionary(new { DirectorId = Director.DirectorId }))'">Modifier</button>
                        </td>

                    </tr>
                </tbody>

            }
        </table>
  
    }
</div>

GoodBurger/Views/Director/ListAllDirector.cshtml
@model System.Collections.Generic.List<DirectorEntity>
@using GoodBurger.Models.Entities
@{
    List<DirectorEntity> AllOwner = ViewData["AllOwner"] as List<DirectorEntity>;
}

<div class="list-group">

    <fieldset>
        <legend>Selectionner le directeur (Resposable) du restaurant :</legend>
        @foreach (DirectorEntity Director in AllOwner)
        {
        <div>
            <input type="radio" id="Director" name="Director" value="@Director.DirectorId">
            <label for="coding">@Director.FirstName @Director.LastName </label>
            <label for="coding">@Director.Email @Director.Phone</label>
        </div>

        }
    </fieldset>
</div>